# Generated by Django 3.2 on 2026-03-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_group', '0002_auto_20230302_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgroup',
            name='users',
        ),
    ]
