# Generated by Django 3.2 on 2026-03-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_tournamentsplitelimination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentInvite',
        ),
    ]
