name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: 69tgugtg%^fgJO&*&
        DB_NAME: github_actions
        DB_USER: postgres
        DB_PASSWORD: postgres
        DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
        DEBUG: True
        TIME_ZONE: US/Pacific
        CACHE_KEY_PREFIX: Halo
        GOOGLE_AUTH_CLIENT_ID: whocares
        GOOGLE_AUTH_CLIENT_SECRET: whocares2
        EMAIL_ID: dunno
        EMAIL_PASSWORD: dunno2
        AWS_ACCESS_KEY_ID: ndkslgnsdklg
        AWS_SECRET_ACCESS_KEY: gmgglkgmd
        AWS_STORAGE_BUCKET_NAME: fggkfdgfdgd
        AWS_S3_ENDPOINT_URL: https://whocares.com
        AWS_LOCATION: doesnotmatter
        STATIC_URL: https://whocares.com
        STATICFILES_STORAGE: fgdfgdgf
        DEFAULT_FILE_STORAGE: gsdsgsdg
      run: |
        python manage.py test tournament/
        python manage.py test tournament_analytics/tests
        python manage.py test tournament_group/tests
        python manage.py test invite/
